version: '3'

services:
  bundle:
    build: ./bundle
    image: bundle
    container_name: opa-bundle
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ./bundle/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./bundle:/upload/
  logger:
    build: ./logger
    image: logger
    container_name: logger
    restart: always
    ports:
      - "3000:3000"
  opa:
    image: openpolicyagent/opa:0.51.0
    container_name: opa-server
    restart: always
    ports:
      - 8181:8181
    volumes:
      - ./opa:/workspace
    command: ["run", "--server", "-c", "/workspace/config.yaml", "--set-file", "keys.verifier.key=/workspace/public_key.pem"]
    depends_on:
      - bundle
      - logger

  